### PR TITLE
Add missing steps in manual Ecto setup for existing applications

### PR DESCRIPTION
**Pull request by EyMaddis**
I noticed that the guide just adds the the dependencies to `deps`, but they are not listed in the application dependencies. 
This will result in startup errors which might discourage new users joining the ecosystem.

Furthermore it contains the changes for Ecto 3, which are also mentioned in the [migration guide](http://www.phoenixframework.org/blog/upgrading-from-11x-to-120).

### CODE REVIEW

**Comment by EyMaddis** [comment]
I added that the `web/web.ex` should include model dependencies in order to generate models

**Comment by jsncmgs1** [comment]
@EyMaddis you should squash [aeb5c84], possibly all 3 but definitely the typo :)

**Comment by EyMaddis** [comment]
@jsncmgs1 there are now only two commits left :)

**Comment by Gazler** [comment]
Thanks, I've just added one comment then this is good to go.

**Comment by EyMaddis** [comment]
@Gazler I adapted your suggestion, but also included what the line does, so it is more beginner friendly. I did learned the semantics of this within the process of migration, so I think that it might be helpful to state that it will import everything globally.

**Comment by Gazler** [comment]
Thanks <3

Closed via https://github.com/phoenixframework/phoenix_guides/commit/775a006df3e8da0b72eb437d912fb94b60ab53ef

**Pull request closed without merging**
