### PR TITLE
Update example tree of default app.

### PR DESCRIPTION
**Pull request by JeroenKnoops**
A new phoenix project does not use scss, but uses css.

`app.scss` --> `app.css`

### CODE REVIEW

**Comment by jeffkreeftmeijer** [comment]
Hey @JeroenKnoops, nice find! There's another one in https://github.com/phoenixframework/phoenix_guides/blob/cd81b655f85e6d6b954e0aae4a9ce42f421f68b9/bonus_guides/D_mix_tasks.md#L444, could you update that too and squash? Just so we have fixed this once and for all. :)

**Comment by lancehalvorsen** [comment]
@JeroenKnoops, thanks for submitting this! I agree with @jeffkreeftmeijer, if you could change the other instance of this error in this PR, that would be really nice.

Thanks!

**Comment by JeroenKnoops** [comment]
Updated the update! :)

**Comment by lancehalvorsen** [comment]
Awesome! Thanks @JeroenKnoops! <3 <3 <3

**Pull request merged**
