### PR TITLE
Updates mix task references in doc

### PR DESCRIPTION
**Pull request by alvincrespo**
Recently I was trying to figure out how to list out the routes in my app to the terminal. In doing so I found that the docs were not up to date with the grep task listed in the mix tasks bonus guide. This PR is focused on updating the docs to reflect the latest tasks under the phx module while supporting the current phoenix module.

## Changes

- Updates grep usage to lookup `phx` instead of `phoenix`
- Updates reference of `phoenix` in the doc to `phx`
- Creates a note to ensure reader understands there are still tasks under the `phoenix` module
- Removes note about `phoenix.start` since its a pretty old reference

### CODE REVIEW

**Comment by alvincrespo** [comment]
I apologize if my terminology is off above, specifically the usage of "module" to refer to a mix task. Please correct me if I'm wrong there. 

Also - let me know if you'd like to see some more enhancements to the doc. I'd more than happy to help 😄

**Comment by alvincrespo** [comment]
Hey everyone! Just curious if I could get some guidance on this PR?

**Comment by chrismccord** [comment]
❤️❤️❤️❤️

**Comment by alvincrespo** [comment]
@chrismccord Ha - that was fast 👍

**Pull request merged**
