### PR TITLE
clarified misleading sentence in ecto_models.md

### PR DESCRIPTION
**Pull request by nhooyr**
cast/3's third argument is the allowed fields, not the required ones.

### CODE REVIEW

**Comment by digitalcake** [comment]
I'll need to double check, but I think the word "required" is correct in that I believe cast asks like a whitelist and that if its not in that list it will not be available in the corresponding pipe. 

IE: 
"All parameters that are not explicitly allowed are ignored."
https://hexdocs.pm/ecto/Ecto.Changeset.html#cast/3

**Comment by nhooyr** [comment]
I don't think the word required gets that meaning across. I think `allowed` is more clear, even the function definition and documentation use allowed and not required. While cast acts like a whitelist, it allows only those on it's whitelist through, validate_required is still required to make sure that the required fields are present.

**Comment by digitalcake** [comment]
why not the word "whitelisted" that an even more concrete terminology that I think gets the point across.

**Comment by nhooyr** [comment]
Done

**Comment by Gazler** [comment]
Sorry I'm late to this. I think we should go for `allowed` as that is what Ecto use in their docs https://hexdocs.pm/ecto/Ecto.Changeset.html#cast/3

**Comment by nhooyr** [comment]
I'll try and update this soon.

**Comment by nhooyr** [comment]
@chrismccord did you close due to inactivity? If so, I can update this now, I just forgot about it.

**Comment by chrismccord** [comment]
Yes, inactivity, sorry. We are in the middle of a big overhaul on Ecto so this will be taken care of along with that effort. Thanks for the PR!

**Pull request closed without merging**
