### PR TITLE
Upgrade section of guides

### PR DESCRIPTION
**Pull request by radar**
Rather than having the (rather excellent) upgrade guides hidden away in Gists by @chrismccord, I think they should be made a prominent feature of the guides (similar to how Rails has an [upgrading guide](http://guides.rubyonrails.org/upgrading_ruby_on_rails.html)).

I've added an example of one of those guides here and want to open this PR and discussion before I go doing any more work on it.

### CODE REVIEW

**Comment by lancehalvorsen** [comment]
Thanks @radar for taking the time to create this PR! Here's the history on the Upgrade Guides.

There used to be an individual guide for each upgrade, eg. 0.11.0 to 0.12.0. They were all located in the Bonus Guides section. As you can imagine, they began to pile up and obscure the other guides. What we did to fix this is to create a single Upgrade Guide in the Bonus Guides section that points to the new home of all the Upgrade Guides, the News section.

Here's the Upgrade Guide: http://www.phoenixframework.org/docs/upgrading-phoenix
Here's the News section that it points to: http://www.phoenixframework.org/blog

Since the Phoenix changelog is the source of truth, we didn't duplicate them here in the repo.

I will have time this evening and tomorrow to work on some long overdue PRs here. I'll take care of creating a new News item for this.

**Comment by radar** [comment]
Hey @lancehalvorsen, no pressure :)

The changelogs are a great list of all the things that changed in the bit in between versions. What I'm asking for is a clear + concise upgrade guide between versions; essentially the same as @chrismccord's Gists now, but more... uh, "official". 

Would this be something that we could accomplish?

**Comment by lancehalvorsen** [comment]
Hi @radar, 
Sorry, I got lost in my sense of guilt for neglecting PRs and didn't communicate clearly. ;)

We already have this on the phoenixframework.org site. Here's the same content as the PR: http://www.phoenixframework.org/blog/upgrading-from-v016-to-v017

The thing is, we don't have files for these in this repo because they would just be a copy of @chrismccord's changelog.

To address the missing upgrade content, I just need to go into the admin section of readme.io, which currently hosts the guides, and create a new blog item using the changelog markdown for the upgrade from v1.0 to v1.1.

Did I do a better job this time? :) Please let me know if I'm missing something. Thanks again!

**Comment by radar** [comment]
Yes, that's good :) 

Having the blog posts for 0.17 -> 1.0, and 1.0 -> 1.1 would be great :0

**Comment by lancehalvorsen** [comment]
Awesome! 

Actually, there were no external facing changes for the 0.17 -> 1.0 upgrade, iirc, so there were no upgrade instructions.

The 1.0 -> 1.1 guide will happen this weekend.

**Comment by lancehalvorsen** [comment]
This is now live on the site. Unfortunately, readme.io no longer seems to let me drag and drop the items to set their order, so this new one obscures The Road to 2 Million Websocket Connections in Phoenix.

**Comment by radar** [comment]
Thanks a lot for doing this @lancehalvorsen! :+1:

**Comment by lancehalvorsen** [comment]
:+1:

**Pull request closed without merging**
