### PR TITLE
Fix typo in "Sending Email with SMTP" bonus guide

### PR DESCRIPTION
**Pull request by laurenfackler**
"which will call" to "which we'll call"

### CODE REVIEW

**Comment by willykaram** [comment]
@laurenfackler thanks very much for mentioning that typo and also submitting a PR to correct it. @lancehalvorsen @jeregrine I'd suggest merging this PR if you can.

**Comment by Gazler** [comment]
I believe "will call" is correct in this case. It is saying that each function you define starts with the `new_email` call to initialize the mail struct.This function in question is https://hexdocs.pm/bamboo/0.7.0/Bamboo.Email.html#new_email/1

I can see the potential confusion though. I think if we go ahead and link to the bamboo docs(  https://hexdocs.pm/bamboo/0.7.0/Bamboo.Email.html#new_email/1 ) then this should clarify the intent.

**Comment by laurenfackler** [comment]
@Gazler Ah, I see my confusion. Sorry about that!

**Comment by Gazler** [comment]
@laurenfackler If you want to open a new PR which changes the line:

     `new_email/1` in order to build the email.

To:

    [`new_email/1`](https://hexdocs.pm/bamboo/0.7.0/Bamboo.Email.html#new_email/1) in order to build the email.

Then I'll happily merge it in.

**Comment by laurenfackler** [comment]
@Gazler ✔️  #635

**Pull request closed without merging**
