### PR TITLE
Add nginx upgrade headers to prevent cutting connection.

### PR DESCRIPTION
**Pull request by mgwidmann**
I had trouble getting nginx not to cut the connection and return a 400 to the client without the following `Upgrade` and `Connection` headers.

### CODE REVIEW

**Comment by lancehalvorsen** [comment]
@mgwidmann thanks for this! Question: is this specific to websocket requests for channels or generic HTTP requests?

If it is specific to channels, we should probably put some text around this to tell readers what it's for, and that it may not be necessary if they aren't using channels at all.

**Comment by mgwidmann** [comment]
Yeah, regular requests worked fine. For channels to work, if Nginx is going to act as a websocket proxy, you must add that to the config. See their docs here: http://nginx.com/blog/websocket-nginx/ (down at the bottom).

**Comment by mgwidmann** [comment]
Otherwise you have to tell the front-end code (Javascript or whatever) to connect directly to Phoenix instead of hitting the same domain/port as regular requests.

**Comment by lancehalvorsen** [comment]
Indeed. 

I think it would be great if you could just add a line or two of explanation to the changes in this PR letting folks know what the extra config is about. Really, this would be a slightly re-worded version of the two comments you left above. My sense is that it would help people understand their purpose.

Thank you!

**Comment by mgwidmann** [comment]
@lancehalvorsen Hows that?

**Comment by lancehalvorsen** [comment]
:tada: Thanks so much @mgwidmann! :tada:

**Pull request merged**
