### PR TITLE
Update C# client link

### PR DESCRIPTION
**Pull request by Mazyod**
Hey!

After discussing with the author of the currently referenced library [here][discussion-link], I was advised to start a new initiative, since that repository is no longer maintained.

I have a vested interest in maintaining a solid C# client, since I am shipping it with my Unity game. Hence, I started a new project and would like to give it more exposure to attract contributions for enhancing the library.

Overall, the main gains of this new library for the phoenix community are summarized in the following:

1. An active project which encourages contributions
2. A more friendly, statically-typed API
3. Ships with unit and integrations tests
4. Slightly better documentation
5. Full Unity support

[discussion-link]: https://github.com/jfis/dn-phoenix/issues/3

### CODE REVIEW

**Comment by Gazler** [comment]
I am all for more client libraries, and I think we should include yours in the list. Let's change this to a section and include all the existing libraries for now.

> ### Client Libraries
> #### Official
>  - Javascript
>  - [phoenix.js](https://github.com/phoenixframework/phoenix/blob/v1.2/web/static/js/phoenix.js)
>
> #### 3rd Party
> - Swift (iOS)
>   - [SwiftPhoenix](https://github.com/davidstump/SwiftPhoenixClient)
> - Java (Android)
>   - [JavaPhoenixChannels](https://github.com/eoinsha/JavaPhoenixChannels)
> - C#
>   - [PhoenixSharp](https://github.com/Mazyod/PhoenixSharp)
>   - [dn-phoenix](https://github.com/jfis/dn-phoenix)

**Comment by Mazyod** [comment]
@Gazler Sure, sounds like a great idea. However, wouldn't it be more useful to somehow indicate which ones are active, and which are no longer maintained?

I'll make the change regardless, and leave the decision to you.

**Comment by Mazyod** [comment]
@Gazler done

**Comment by Gazler** [comment]
Thanks <3 Hopefully people will be able to see which clients are in active development by the commit date. It may be the case that people are running an older version of Phoenix and need to use an older client.

**Pull request merged**
