### PR TITLE
Heroku fixes

### PR DESCRIPTION
**Pull request by carols10cents**
Hi! I just have a few little tweaks based on the heroku deploy I just did; I found a few small differences between what the guide said and what I actually needed to do/what actually happened.

Overall, though, everything went great!!! :tada: :balloon: :fireworks:

### CODE REVIEW

**Comment by stevedomin** [comment]
Hi @carols10cents 

The `{:system, "PORT"}` syntax is a workaround for Erlang releases so that Phoenix get the PORT environment at runtime (instead of it happening during the release process).

As such it shouldn't be used for Heroku. Having two syntax is slightly annoying but that's the only way to make it work for releases at the moment.

**Comment by lancehalvorsen** [comment]
Hi @carols10cents,

Thanks so much for your contribution, and very glad to hear that your deployment went smoothly overall! Yay!

I'm curious if the `System.get_env("PORT")]` syntax didn't work for you, or whether there was another reason for the change. (I'm extra curious because it did work for me as well as others who tested the guide before we made it public. Mysteries!)

If it did work, I think we should leave the original syntax for the reasons that @stevedomin gave.

Otherwise, I think the changes are good. When we resolve the syntax, if you could please squash the commits, we'll be good to go.

Thanks so much once again for taking the time to submit this!

**Comment by carols10cents** [comment]
Well now I'm really confused, because I left the original `port: {:system, "PORT"}` syntax there, deployed to heroku, and it seems to be working!

I actually never even tried the `System.get_env("PORT")` syntax since what was there seemed to work. I will try that later and report back, and if it does work, add some more explanation so that someone else doesn't make the same assumption I did :)

**Comment by ericmj** [comment]
Both should work.

**Comment by stevedomin** [comment]
Since we have changed it in Phoenix it probably make sense for this guide to reflect that (https://github.com/phoenixframework/phoenix/commit/feef6076094104e45660637e05629f5869d6d836)

**Comment by lancehalvorsen** [comment]
Sorry friends, I got a bit behind on this one.

Based on the last comments from @ericmj and @stevedomin, I'm going to merge this. The two commits seem distinct enough to leave as is without squashing. So :tada: !

Thanks so much once again @carols10cents!

**Comment by carols10cents** [comment]
Thank you!!! :heart:

**Comment by emilsoman** [comment]
This is kind of confusing now because port is configured using a tuple `{:system, "PORT"}` whereas secret_key_base is configured using `System.get_env("SECRET_KEY_BASE")`. Can we avoid this confusion by sticking to one way of configuring using environment variables if possible ? Thanks :)

**Comment by jeregrine** [comment]
@emilsoman the {:system, "PORT"} is a pattern used by phoenix specifically. Not generally in elixir, it is inconsistent.

**Comment by emilsoman** [comment]
@jeregrine Yes, and only PORT configuration uses this pattern. It could lead to confusion since users will expect other configurations to work this way. We can either:

1. Clearly document that PORT is the only configuration that works with a tuple, or
2. Explain how to do this properly with exrm

Not sure if this is already documented elsewhere.

**Comment by jeregrine** [comment]
@emilsoman great. Would you be willing to PR that change?

**Comment by emilsoman** [comment]
@jeregrine  Sure. Before I do that, do we have a consensus on the idiomatic way to configure production apps ? I can see the community is split on this : 
1. Use `System.get_env` in config files and compile with environment variables
2. Use exrm and substitute `"${ENV_VAR}"` in config files using `RELX_REPLACE_OS_VARS=true` like [this](http://blog.plataformatec.com.br/2016/05/how-to-config-environment-variables-with-elixir-and-exrm/)
3. Use conform with exrm like [this](https://github.com/bitwalker/exrm/blob/master/docs/Release%20Configuration.md)
4. Write code that can evaluate environment variables at runtime and use config values as fallback like [this](https://github.com/phoenixframework/phoenix/issues/354)

Until then, I think the documentation should go into API doc [here](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint.ex#L131-L135) to warn users that `{:system, "ENV_VAR"}` is for port only. What do you think ?

**Comment by jeregrine** [comment]
Exrm isn't used on Heroku, thus Exrm and Conform are not used, Conform is not a community standard, it is a third party optional library that Exrm chooses to use. 

If you'd like to PR a change into Phoenix to make it more explicit, you are more than welcome. If you'd like to add a line clarifying in this guide the different usages of System.get_env and {:system, "PORT"} please do. 

Finding a community consensus is not relevant to this project and would be more applicable on the forum or mailing list.

**Pull request merged**
