### PR TITLE
Update I_exrm_releases.md

### PR DESCRIPTION
**Pull request by zeroows**
Added the "config :phoenix, :serve_endpoints, true"

### CODE REVIEW

**Comment by jeregrine** [comment]
Thanks! @Zeroows <3

**Comment by zeroows** [comment]
Thank you, Can you add "**advanced-deployment**" and "**deployment**" to the menu <3

**Comment by jeregrine** [comment]
@zeroows I don't follow?

**Comment by zeroows** [comment]
@jeregrine never mind, I didn't see the link in the guide. You are doing a great job guys. Thank you.

**Pull request merged**
