### PR TITLE
Focus on Ecto rather than Cowboy on overview

### PR DESCRIPTION
**Pull request by josevalim**

### CODE REVIEW

**Comment by josevalim** [comment]
Btw, what do you think about splitting the `Using MySQL` section from the Ecto guide into a Bonus Guide? With more database support coming, it would be nice to have multiple sections. @michalmuskala could help us with a `Using MongoDB` guide once his work is done!

**Comment by michalmuskala** [comment]
I'll be happy to help with the guides once the adapter is working well enough to be used.

**Comment by lancehalvorsen** [comment]
@josevalim thank you! I'm definitely :+1:  on raising Ecto's profile in the Overview.

I'm also :+1: on breaking out the `Using MySQL` section into a Bonus Guide. I'll create an issue for that now.

@michalmuskala thank you as well! I would love your help when you feel ready.

**Comment by jeregrine** [comment]
@josevalim great call! Nobody really *needs* to know about cowboy/ranch at all.

**Pull request merged**
